name: build

on:
  - push
  - pull_request

jobs:
  build:
    name: "Build for ${{ matrix.bits }}-bit"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]
    steps:
      - uses: actions/checkout@v4

      - name: Checkout src
        uses: actions/checkout@v4
        with:
          repository: minetest/minetest
          path: luanti
          ref: 5.12.0

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gettext

      - name: Build
        run: |
           ./build.sh ${{ matrix.bits }}

      - uses: actions/upload-artifact@v4
        with:
          name: "mingw${{ matrix.bits }}"
          path: B/build/*.7z
          if-no-files-found: error
